version: "3.2"
services:
  neo4j:
    image: neo4j:latest
    container_name: neo4j-test
    ports:
      - 7474:7474
      - 7687:7687
    env_file:
      - ./data/test.env
    restart: on-failure
    networks:
        - neo4j_go_net
    command: neo4j
  
  test_webserver:
    build: 
      context: ./testing/
    ports: 
      - 8000:8000
    volumes:
      - ./testing/:/app/

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_storage:/data
    env_file:
      - ./data/test.env
    command: server --console-address ":9001" /data

networks:
  neo4j_go_net:
    driver: bridge

volumes:
  dgraph:
  minio_storage: {}